name = "DebugDataWriter"
uuid = "810e33c6-efd6-4462-86b1-f71ae88af720"
authors = ["Roman S. Samarev <samarev@acm.org> and contributors"]
version = "0.1.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
JSON3 = "1"
PrettyTables = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
